# Generated by Django 3.2.8 on 2021-12-27 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Amount', models.BigIntegerField()),
                ('Date', models.DateTimeField()),
                ('Choose', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=250)),
                ('My_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='My_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
